version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DOMAIN=your-domain.com
      - ENVIRONMENT=production
    volumes:
      - ./media:/app/media
      - ./training_data:/app/training_data
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data:
