name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/llama-app:latest .
        docker push ${{ secrets.DOCKER_HUB_USERNAME }}/llama-app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.DIGITALOCEAN_SSH_KEY }}
        known_hosts: 'just-a-placeholder-so-we-dont-get-errors'

    - name: Deploy to DigitalOcean
      run: |
        ssh -o StrictHostKeyChecking=no root@${{ secrets.DIGITALOCEAN_HOST }} "
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/llama-app:latest &&
          docker stop app || true &&
          docker rm app || true &&
          docker run -d --name app -p 8000:8000 ${{ secrets.DOCKER_HUB_USERNAME }}/llama-app:latest
        "