name: Deploy to DigitalOcean

on:
  push:
    branches: ["main", "storage_bucket"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push frontend
        uses: docker/build-push-action@v4
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/shape-frontend:latest

      - name: Build and push backend
        uses: docker/build-push-action@v4
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/shape-backend:latest

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.DIGITAL_OCEAN_SSH_KEY }}
          known_hosts: 'just-a-placeholder-so-we-dont-get-errors'
          
      - name: Add host key to known_hosts
        run: ssh-keyscan -H ${{ secrets.DIGITAL_OCEAN_HOST }} >> ~/.ssh/known_hosts

      - name: Copy configuration files
        run: |
          scp docker-compose.prod.yml root@${{ secrets.DIGITAL_OCEAN_HOST }}:/root/docker-compose.yml
          scp .env.prod root@${{ secrets.DIGITAL_OCEAN_HOST }}:/root/.env
          scp nginx.conf root@${{ secrets.DIGITAL_OCEAN_HOST }}:/root/nginx.conf

      - name: Deploy to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no root@${{ secrets.DIGITAL_OCEAN_HOST }} "
            # Pull the latest images
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/shape-frontend:latest
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/shape-backend:latest
            docker pull ollama/ollama:latest

            # Create required directories
            mkdir -p /root/media
            mkdir -p /root/training_data

            # Stop and remove existing containers
            docker compose down || true

            # Start services with new images
            docker compose up -d

            # Clean up old images
            docker image prune -f
          "
